# Generalized Linear Regression

## This is Multiple Linear Regression on diabetes dataset (CampusX)

## Library

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

In [14]:
from sklearn.datasets import load_diabetes

In [15]:
data = load_diabetes()

In [16]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [17]:
data['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [18]:
data['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [19]:
df = pd.DataFrame(data = data['data'], columns = data['feature_names'])

In [20]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [21]:
data['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [22]:
df['target'] = data['target']

In [23]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

## Train Test Split

In [24]:
l = [1,2,3,4,5]
print(l[:-1])
print(l[-1])

[1, 2, 3, 4]
5

In [25]:
# x = df['TV']
# x

In [26]:
# x.ndim

#### Here the dimension of x is 1 which will cause error in train test split ,since tran test split expects x to be 2 dimensional.

#### so the way we can do is 
#### i)  x = np.array(df['TV']).reshape(len(x),1)
#### ii) x = df[['TV']]
#### ii) x = df[df.columns[:-1]]

In [27]:
# x = np.array(df['TV']).reshape(len(x),1)
# x
# x.ndim

In [28]:
# x = df[['TV']]
# x
# x.ndim

In [29]:
x = df[df.columns[:-1]]
x

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [30]:
x.ndim

2

In [31]:
y = df[df.columns[-1:]]
y

     target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [32]:
y.ndim

2

In [33]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [34]:
x_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
70,-0.001882,-0.044642,-0.069797,-0.012556,-0.000193,-0.009143,0.070730,-0.039493,-0.062917,0.040343
37,-0.009147,-0.044642,0.011039,-0.057313,-0.024960,-0.042963,0.030232,-0.039493,0.017036,-0.005220
170,0.023546,0.050680,-0.020218,-0.036656,-0.013953,-0.015092,0.059685,-0.039493,-0.096435,-0.017646
400,-0.023677,-0.044642,0.045529,0.090729,-0.018080,-0.035447,0.070730,-0.039493,-0.034522,-0.009362
286,-0.038207,-0.044642,-0.054707,-0.077970,-0.033216,-0.086490,0.140681,-0.076395,-0.019198,-0.005220
...,...,...,...,...,...,...,...,...,...,...
299,0.038076,0.050680,-0.013751,-0.015999,-0.035968,-0.021982,-0.013948,-0.002592,-0.025953,-0.001078
22,-0.085430,-0.044642,-0.004050,-0.009113,-0.002945,0.007767,0.022869,-0.039493,-0.061176,-0.013504
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
15,-0.052738,0.050680,-0.018062,0.080401,0.089244,0.107662,-0.039719,0.108111,0.036060,-0.042499
168,0.001751,0.050680,0.059541,-0.002228,0.061725,0.063195,-0.058127,0.108111,0.068986,0.127328

In [35]:
x_train = x_train.reset_index()
x_train

,index,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,70,-0.001882,-0.044642,-0.069797,-0.012556,-0.000193,-0.009143,0.070730,-0.039493,-0.062917,0.040343
1,37,-0.009147,-0.044642,0.011039,-0.057313,-0.024960,-0.042963,0.030232,-0.039493,0.017036,-0.005220
2,170,0.023546,0.050680,-0.020218,-0.036656,-0.013953,-0.015092,0.059685,-0.039493,-0.096435,-0.017646
3,400,-0.023677,-0.044642,0.045529,0.090729,-0.018080,-0.035447,0.070730,-0.039493,-0.034522,-0.009362
4,286,-0.038207,-0.044642,-0.054707,-0.077970,-0.033216,-0.086490,0.140681,-0.076395,-0.019198,-0.005220
...,...,...,...,...,...,...,...,...,...,...,...
348,299,0.038076,0.050680,-0.013751,-0.015999,-0.035968,-0.021982,-0.013948,-0.002592,-0.025953,-0.001078
349,22,-0.085430,-0.044642,-0.004050,-0.009113,-0.002945,0.007767,0.022869,-0.039493,-0.061176,-0.013504
350,72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
351,15,-0.052738,0.050680,-0.018062,0.080401,0.089244,0.107662,-0.039719,0.108111,0.036060,-0.042499
352,168,0.001751,0.050680,0.059541,-0.002228,0.061725,0.063195,-0.058127,0.108111,0.068986,0.127328

In [36]:
y_train

     target
70     48.0
37    276.0
170    47.0
400   175.0
286    60.0
..      ...
299    83.0
22     68.0
72    202.0
15    171.0
168   268.0

[353 rows x 1 columns]

# Linear Regression

In [37]:
n = len(x_train.columns)
n

11

In [38]:
A = np.zeros((n,n))
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
H = np.zeros((n,1))
H

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
for i in range(n):
    for j in range(n):
        if i==0 and j==0 :
            A[i,j] = len(x_train)
        else:
            if i==0 :
                A[i,j] = x_train[x_train.columns[j]].sum()
            elif j==0 :
                A[i,j] = x_train[x_train.columns[i]].sum()
            else :
                A[i,j] = (x_train[x_train.columns[i]] * x_train[x_train.columns[j]]).sum()

A

array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
        -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
        -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
        -1.03738610e-01, -3.39006149e-01],
       [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
         1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
         1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
         2.54930348e-01,  2.86247901e-01],
       [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
         7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
         8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
         1.08678991e-01,  1.87427433e-01],
       [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
         7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
         2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
         3.59480196e-01,  3.15896870e-01],
       [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
         3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
         1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
         3.04464679e-01,  2.97854701e-01],
       [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
         1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
         7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
         4.13749952e-01,  2.48780554e-01],
       [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
         2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
         7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
         2.57005508e-01,  2.33675449e-01],
       [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
        -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
        -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
        -3.21220842e-01, -2.14128115e-01],
       [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
         3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
         5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
         4.84523897e-01,  3.13813701e-01],
       [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
         3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
         2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
         8.07339176e-01,  3.40901470e-01],
       [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
         3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
         2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
         3.40901470e-01,  7.77878199e-01]])

In [41]:
for i in range(n):
    if i==0 :
        H[i,0] = y_train[y_train.columns[0]].sum()
    else :
        H[i,0] = (x_train[x_train.columns[i]].values * y_train[y_train.columns[0]].values).sum()

H

array([[ 5.31120000e+04],
       [ 2.91448356e+02],
       [-6.26449400e+00],
       [ 6.61971083e+02],
       [ 5.80945727e+02],
       [ 2.33223872e+02],
       [ 1.21718274e+02],
       [-3.74487985e+02],
       [ 3.85769930e+02],
       [ 7.47793302e+02],
       [ 4.21559895e+02]])

In [42]:
A_list = list()

for j in range(n):
    temp_A = A.copy()
    temp_A[:,j] = H.reshape(n,)
    A_list.append(temp_A)

A_list

[array([[ 5.31120000e+04, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [ 2.91448356e+02,  8.20967496e-01,  1.41874960e-01,
          1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-6.26449400e+00,  1.41874960e-01,  7.95580922e-01,
          7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [ 6.61971083e+02,  1.80487652e-01,  7.04549395e-02,
          7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [ 5.80945727e+02,  2.83447221e-01,  1.79747998e-01,
          3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [ 2.33223872e+02,  2.35892391e-01,  2.63140905e-04,
          1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [ 1.21718274e+02,  1.90418063e-01,  8.60276097e-02,
          2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [-3.74487985e+02, -6.31103606e-02, -2.99960819e-01,
         -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [ 3.85769930e+02,  1.84124182e-01,  2.57031428e-01,
          3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [ 7.47793302e+02,  2.54930348e-01,  1.08678991e-01,
          3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [ 4.21559895e+02,  2.86247901e-01,  1.87427433e-01,
          3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02,  5.31120000e+04, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  2.91448356e+02,  1.41874960e-01,
          1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01, -6.26449400e+00,  7.95580922e-01,
          7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  6.61971083e+02,  7.04549395e-02,
          7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  5.80945727e+02,  1.79747998e-01,
          3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.33223872e+02,  2.63140905e-04,
          1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.21718274e+02,  8.60276097e-02,
          2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -3.74487985e+02, -2.99960819e-01,
         -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  3.85769930e+02,  2.57031428e-01,
          3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  7.47793302e+02,  1.08678991e-01,
          3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  4.21559895e+02,  1.87427433e-01,
          3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02,  5.31120000e+04,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  2.91448356e+02,
          1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01, -6.26449400e+00,
          7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  6.61971083e+02,
          7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  5.80945727e+02,
          3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.33223872e+02,
          1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  1.21718274e+02,
          2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -3.74487985e+02,
         -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  3.85769930e+02,
          3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  7.47793302e+02,
          3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  4.21559895e+02,
          3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
          5.31120000e+04, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
          2.91448356e+02,  2.83447221e-01,  2.35892391e-01,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
         -6.26449400e+00,  1.79747998e-01,  2.63140905e-04,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
          6.61971083e+02,  3.35896866e-01,  1.99230748e-01,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
          5.80945727e+02,  8.00195622e-01,  1.98146915e-01,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
          2.33223872e+02,  1.98146915e-01,  7.94563676e-01,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
          1.21718274e+02,  1.55205364e-01,  7.08557334e-01,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
         -3.74487985e+02, -1.31094721e-01,  4.53907433e-02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
          3.85769930e+02,  2.01978040e-01,  4.27047853e-01,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
          7.47793302e+02,  3.04464679e-01,  4.13749952e-01,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
          4.21559895e+02,  2.97854701e-01,  2.48780554e-01,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01,  5.31120000e+04, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
          1.80487652e-01,  2.91448356e+02,  2.35892391e-01,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
          7.04549395e-02, -6.26449400e+00,  2.63140905e-04,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
          7.92372628e-01,  6.61971083e+02,  1.99230748e-01,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
          3.35896866e-01,  5.80945727e+02,  1.98146915e-01,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
          1.99230748e-01,  2.33223872e+02,  7.94563676e-01,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
          2.15252524e-01,  1.21718274e+02,  7.08557334e-01,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
         -2.94169684e-01, -3.74487985e+02,  4.53907433e-02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
          3.22034052e-01,  3.85769930e+02,  4.27047853e-01,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
          3.59480196e-01,  7.47793302e+02,  4.13749952e-01,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
          3.15896870e-01,  4.21559895e+02,  2.48780554e-01,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01,  5.31120000e+04,
         -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
          1.80487652e-01,  2.83447221e-01,  2.91448356e+02,
          1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
          7.04549395e-02,  1.79747998e-01, -6.26449400e+00,
          8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
          7.92372628e-01,  3.35896866e-01,  6.61971083e+02,
          2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
          3.35896866e-01,  8.00195622e-01,  5.80945727e+02,
          1.55205364e-01, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
          1.99230748e-01,  1.98146915e-01,  2.33223872e+02,
          7.08557334e-01,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
          2.15252524e-01,  1.55205364e-01,  1.21718274e+02,
          7.88957953e-01, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
         -2.94169684e-01, -1.31094721e-01, -3.74487985e+02,
         -1.54216283e-01,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
          3.22034052e-01,  2.01978040e-01,  3.85769930e+02,
          5.17293149e-01, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
          3.59480196e-01,  3.04464679e-01,  7.47793302e+02,
          2.57005508e-01, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
          3.15896870e-01,  2.97854701e-01,  4.21559895e+02,
          2.33675449e-01, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
          5.31120000e+04,  8.14279161e-01, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
          1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
          2.91448356e+02, -6.31103606e-02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
          7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
         -6.26449400e+00, -2.99960819e-01,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
          7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
          6.61971083e+02, -2.94169684e-01,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
          3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
          5.80945727e+02, -1.31094721e-01,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
          1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
          2.33223872e+02,  4.53907433e-02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
          2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
          1.21718274e+02, -1.54216283e-01,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
         -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
         -3.74487985e+02,  7.95457225e-01, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
          3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
          3.85769930e+02, -5.61029109e-01,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
          3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
          7.47793302e+02, -3.21220842e-01,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
          3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
          4.21559895e+02, -2.14128115e-01,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  5.31120000e+04, -9.51231584e-01,
         -1.03738610e-01, -3.39006149e-01],
        [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
          1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
          1.90418063e-01,  2.91448356e+02,  1.84124182e-01,
          2.54930348e-01,  2.86247901e-01],
        [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
          7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
          8.60276097e-02, -6.26449400e+00,  2.57031428e-01,
          1.08678991e-01,  1.87427433e-01],
        [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
          7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
          2.15252524e-01,  6.61971083e+02,  3.22034052e-01,
          3.59480196e-01,  3.15896870e-01],
        [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
          3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
          1.55205364e-01,  5.80945727e+02,  2.01978040e-01,
          3.04464679e-01,  2.97854701e-01],
        [-3.39194171e-01,  2.35892391e-01,  2.63140905e-04,
          1.99230748e-01,  1.98146915e-01,  7.94563676e-01,
          7.08557334e-01,  2.33223872e+02,  4.27047853e-01,
          4.13749952e-01,  2.48780554e-01],
        [-7.01634988e-01,  1.90418063e-01,  8.60276097e-02,
          2.15252524e-01,  1.55205364e-01,  7.08557334e-01,
          7.88957953e-01,  1.21718274e+02,  5.17293149e-01,
          2.57005508e-01,  2.33675449e-01],
        [ 8.14279161e-01, -6.31103606e-02, -2.99960819e-01,
         -2.94169684e-01, -1.31094721e-01,  4.53907433e-02,
         -1.54216283e-01, -3.74487985e+02, -5.61029109e-01,
         -3.21220842e-01, -2.14128115e-01],
        [-9.51231584e-01,  1.84124182e-01,  2.57031428e-01,
          3.22034052e-01,  2.01978040e-01,  4.27047853e-01,
          5.17293149e-01,  3.85769930e+02,  7.44324811e-01,
          4.84523897e-01,  3.13813701e-01],
        [-1.03738610e-01,  2.54930348e-01,  1.08678991e-01,
          3.59480196e-01,  3.04464679e-01,  4.13749952e-01,
          2.57005508e-01,  7.47793302e+02,  4.84523897e-01,
          8.07339176e-01,  3.40901470e-01],
        [-3.39006149e-01,  2.86247901e-01,  1.87427433e-01,
          3.15896870e-01,  2.97854701e-01,  2.48780554e-01,
          2.33675449e-01,  4.21559895e+02,  3.13813701e-01,
          3.40901470e-01,  7.77878199e-01]]),
 array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
         -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
         -7.01634988e-01,  8.14279161e-01,  5.31120000e+04,
         -1.03738610e-01, -3.39006149e-01],

In [43]:
b_list = list()

for i in range(n):
    b = np.linalg.det(A_list[i]) / np.linalg.det(A)
    b_list.append(b)

b_list

[151.88331005254176,
 -9.158653181170267,
 -205.45432163451844,
 516.6937445408216,
 340.6199990455475,
 -895.5520019034392,
 561.2206790412738,
 153.89310953634168,
 126.7313968784539,
 861.1270015229846,
 52.42112237904708]

In [44]:
print('intercept :',b_list[0])

intercept : 151.88331005254176

In [45]:
print('coefficients :')
for i in range(1,n):
    print('b'+str(i),':',b_list[i])

coefficients :
b1 : -9.158653181170267
b2 : -205.45432163451844
b3 : 516.6937445408216
b4 : 340.6199990455475
b5 : -895.5520019034392
b6 : 561.2206790412738
b7 : 153.89310953634168
b8 : 126.7313968784539
b9 : 861.1270015229846
b10 : 52.42112237904708

In [46]:
x_test

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
212,0.067136,-0.044642,0.003494,0.035644,0.049341,0.031254,0.070730,-0.039493,-0.000612,0.019633
422,-0.078165,0.050680,0.077863,0.052858,0.078236,0.064447,0.026550,-0.002592,0.040673,-0.009362
67,0.041708,0.050680,-0.014828,-0.017135,-0.005697,0.008394,-0.013948,-0.001854,-0.011897,0.003064
89,-0.045472,-0.044642,-0.048241,-0.019442,-0.000193,-0.016032,0.067048,-0.039493,-0.024795,0.019633
390,0.009016,0.050680,0.069241,0.059744,0.017694,-0.023234,-0.047082,0.034309,0.103297,0.073480
...,...,...,...,...,...,...,...,...,...,...
129,0.009016,-0.044642,0.016428,0.004658,0.009439,0.010586,-0.028674,0.034309,0.038968,0.119043
417,-0.052738,-0.044642,0.071397,-0.074527,-0.015328,-0.001314,0.004460,-0.021412,-0.046883,0.003064
332,0.030811,-0.044642,0.104809,0.076958,-0.011201,-0.011335,-0.058127,0.034309,0.057108,0.036201
150,0.023546,-0.044642,0.070319,0.025315,-0.034592,-0.014466,-0.032356,-0.002592,-0.019198,-0.009362
192,0.056239,0.050680,-0.030996,0.008101,0.019070,0.021233,0.033914,-0.039493,-0.029526,-0.059067

In [47]:
y_test

     target
212    73.0
422   233.0
67     97.0
89    111.0
390   277.0
..      ...
129   268.0
417    55.0
332   270.0
150   288.0
192    91.0

[89 rows x 1 columns]

In [48]:
# y_prediction

y_cap = list()
y_prediction = b_list[0]

for row in x_test.index:
    for i in range(len(x_test.columns)):
        y_prediction = y_prediction + b_list[i+1] * x_test[x_test.columns[i]][row]
    
    y_cap.append(y_prediction)
    y_prediction = b_list[0]

y_cap

[154.12138809538376,
 204.818351176521,
 124.9375535286967,
 106.08950892826078,
 258.5348575985564,
 256.3310074008192,
 118.75087616091737,
 119.52440696107134,
 101.50816734991409,
 190.54048660815025,
 141.70656811061934,
 172.5188396146562,
 174.33861648821417,
 134.80942706126197,
 294.1399453657877,
 94.11798038458262,
 211.97059794859257,
 156.49579378119438,
 134.21000428481747,
 119.62664644088329,
 148.87842251198688,
 165.0087340928782,
 151.10021037547702,
 176.04063756372508,
 133.27769647287874,
 221.2955539224729,
 197.17324941409564,
 96.15776879970183,
 50.26012710959104,
 230.4858031667959,
 242.06073865938308,
 114.11129217711607,
 67.07532416760374,
 94.52943824732797,
 201.2141537523553,
 167.05136201269315,
 159.88126799729832,
 192.78746658751788,
 114.49551325245086,
 233.4823455129934,
 140.82563044691435,
 121.06804090464499,
 192.2748077151154,
 191.127388452389,
 179.16865787866428,
 148.34935601317437,
 163.47414621761712,
 276.81647883846244,
 100.17926431639233,
 164.1055529756316,
 255.8076218869283,
 136.9466203974688,
 152.37503698927478,
 107.92237882178244,
 194.21924677997163,
 77.34670792324725,
 118.504824789682,
 68.38335762826249,
 154.2925852895303,
 162.48840259273172,
 168.36788325871785,
 156.8779032227415,
 97.14191796912228,
 238.16712149650363,
 145.4617990381597,
 117.65702432598293,
 168.88784310744077,
 198.38683887355123,
 118.24053714311377,
 124.6455281194952,
 223.1770036781391,
 200.63012385984808,
 129.54414665715072,
 158.1584764970047,
 154.33256500297205,
 114.47070768978253,
 70.44906407019941,
 76.39738790221342,
 172.41584590630987,
 80.56270076704232,
 80.27228340046075,
 89.46150247599809,
 186.21572052316006,
 275.4627540336108,
 208.26784221748062,
 143.79451509378254,
 291.2876684643834,
 206.3247484413814,
 94.22935404453403]

In [49]:
len(y_cap)

89

## Model Evaluation on Test Dataset

In [50]:
y_test

     target
212    73.0
422   233.0
67     97.0
89    111.0
390   277.0
..      ...
129   268.0
417    55.0
332   270.0
150   288.0
192    91.0

[89 rows x 1 columns]

In [51]:
# R Square

y_mean = y_test[y_test.columns[0]].mean()

sum1 = 0
sum2 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

for i in y_test.index:
    diff = y_test[y_test.columns[0]][i] - y_mean
    sum2 = sum2 + (diff ** 2)

r2 = 1 - (sum1 / sum2)

print(r2)

0.43993386615689656

In [52]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_cap) # first comes actual value and then predicted value
print(r2)

0.4399338661568968

In [53]:
# MSE

sum1 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

mse = sum1 / (len(y_cap))
print(mse)

3094.4566715660635

In [54]:
# RMSE

rmse = np.sqrt(mse)
rmse
print(rmse)

55.62784079546916

In [55]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_cap)
print('MSE :',mse)
rmse = np.sqrt(mse)
print('RMSE :',rmse)

MSE : 3094.4566715660626
RMSE : 55.627840795469155